const {
  getInventories,
  addInventory,
  getInventoryProducts,
  updateInventory,
  deleteInventory,
  getFaultyInventories,
  addFaultyInventory,
  getFaultyInventoryDetails,
  updateFaultyInventory,
  deletefaultyInventory,
  getReturnInventories,
  addReturnInventory,
  getReturnInventoryDetails,
  updateReturnInventory,
  deleteReturnInventory,

} = require('./inventory.controllers');

module.exports = {
  getInventories,
  addInventory,
  getInventoryProducts,
  updateInventory,
  deleteInventory,
  getFaultyInventories,
  addFaultyInventory,
  getFaultyInventoryDetails,
  updateFaultyInventory,
  deletefaultyInventory,
  getReturnInventories,
  addReturnInventory,
  getReturnInventoryDetails,
  updateReturnInventory,
  deleteReturnInventory,
};
